###jdbc
##jdbc.className = com.mysql.jdbc.Driver
##jdbc.url = jdbc:mysql://localhost:3306/skijumper?autoReconnect=true&useSSL=false
##jdbc.user = root
##jdbc.password = mortall1994
#
#spring:
#  jpa:
#    hibernate.ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://localhost:3306/skijumper?autoReconnect=true&useSSL=false
#    username: root
#    password: mortall1994
#server:
#  port: 8090
#  name: skiJump
#
###skijumping
##hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
##hibernate.show_sql = true
##hibernate.hbm2ddl.auto = create
#
