#second, minute, hour, day of month, month, day(s) of week
skijumping:
  settings:
    host: ${HOST:https://www.fis-ski.com/DB/ski-jumping/calendar-results.html?seasoncode=%s&seasonmonth=%02d-%s}
    eventHost: ${EVENT_HOST:https://www.fis-ski.com/DB/general/event-details.html?sectorcode=JP&eventid=%s&seasoncode=%s}
    jumpResultHost: ${JUMP_RESULT_HOST:https://www.fis-ski.com/DB/general/results.html?sectorcode=JP&raceid=%s}

    hostWithFilterForYear: ${HOST:http://www.fis-ski.com/ski-jumping/events-and-places/results/?season=}
    skiJumpingResultsHost: ${HOST:https://data.fis-ski.com/dynamic/results.html?sector=JP&raceid=}
    directory: ${DIRECTORY:tmp}
    loadAllData: ${DOWNLOAD_ALL_BASIC_DATA:false}
    numberOfPreviousMonth: ${NUMBER_OF_PREVIOUSE_MONTH_TO_DOWNLOAD:1}
    skiJumperDataHost: ${SKI_JUMPER_DATA_HOST:https://www.fis-ski.com/DB/general/athlete-biography.html?sectorcode=jp&competitorid=%s&type=result}
    scheduler:
      importData:
        cron: ${SKI_JUMPING_SETTINGS_DATA_IMPORT_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_DATA_IMPORT_ENABLE:true}
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:SkiJumping}
    queues:
      sourceImportEventListener: ${SKI_JUMPING_SOURCE_IMPORT_EVENT_LISTENER:sourceImportEventListener}
      importEventIdListener: ${SKI_JUMPING_IMPORT_EVENT_ID_LISTENER:importEventIdListener}
      importDataRaceEventListener: ${SKI_JUMPING_IMPORT_DATA_RACE_EVENT_LISTENER:importDataRaceEventListener}
      importPlaceEventListener: ${SKI_JUMPING_IMPORT_PLACE_EVENT_LISTENER:importPlaceEventListener}
      importJumpResultEventListener: ${SKI_JUMPING_IMPORT_JUMP_RESULT_EVENT_LISTENER:importJumpResultEventListener}
      importJumpResultTeamEventListener: ${SKI_JUMPING_IMPORT_JUMP_RESULT_TEAM_EVENT_LISTENER:importJumpResultTeamEventListener}
      importSkiJumperDataListener: ${IMPORT_SKI_JUMPER_DATA_LISTENER:importSkiJumperDataListener}

spring:
  profiles:
    active: ${DEV_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: ${hibernate.ddl-auto:none}
  datasource:
    url: ${URL:jdbc:mysql://mariadb:3306/skijumper?autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${USER:root}
    password: ${PASSWORD:mortall1994}
  batch:
    job:
      enabled: ${ENABLE:false}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
