skijumping:
  settings:
    host: ${HOST:http://www.fis-ski.com/ski-jumping/events-and-places/results/}
    hostWithFilterForYear: ${HOST:http://www.fis-ski.com/ski-jumping/events-and-places/results/?season=}
    skiJumpingResultsHost: ${HOST:https://data.fis-ski.com/dynamic/results.html?sector=JP&raceid=}
    directory: ${DIRECTORY:tmp}
    fileName: ${FILE_NAME:tmp/SkiJumping.txt}
    loadAllData: ${DOWNLOAD_ALL_BASIC_DATA:false}
    numberOfPreviousYear: ${NUMBER_OF_PREVIOUSE_YEAR_TO_DOWNLOAD:2}
    scheduler:
      #run all jobs in right order
      synchronize:
        cron: ${SKI_JUMPING_SETTINGS_DATA_SYNCHRONIZER_CRON:0 0/1 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_DATA_SYNCHRONIZER_ENABLE:false}
      #first step
      importData:
        cron: ${SKI_JUMPING_SETTINGS_DATA_IMPORT_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_DATA_IMPORT_ENABLE:false}
      #Second step
      findTournamentYear:
        cron: ${SKI_JUMPING_SETTINGS_FIND_TOURNAMENT_YEAR_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_FIND_TOURNAMENT_YEAR_ENABLE:false}
      #Third Step
      findRaceData:
        cron: ${SKI_JUMPING_SETTINGS_FIND_RACE_DATA_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_FIND_RACE_DATA_ENABLE:false}
      #Fourth Step
      basicDataSynchronize:
        cron: ${SKI_JUMPING_SETTINGS_BASIC_DATA_SYNCHRONIZE_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_BASIC_DATA_SYNCHRONIZE_ENABLE:false}
      #fifth Step
      jumpResultSynchronize:
        cron: ${SKI_JUMPING_SETTINGS_RESULT_DATA_SYNCHRONIZE_CRON:0 0/30 * * * *}
        enable: ${SKI_JUMPING_SETTINGS_RESULT_DATA_SYNCHRONIZE_ENABLE:false}
spring:
  jpa:
    database: ${DATABASE:H2}
    hibernate.ddl-auto: ${DDL-AUTO:create-drop}
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
  datasource:
    driverClassName: ${DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${URL:jdbc:h2:mem:testdb}
    username: ${USERNAME:sa}
    password: ${PASSWORD:}
  profiles:
    active: ${TEST_PROFILE:test}
  batch:
    job:
      enabled: ${ENABLE:false}
  h2:
    console:
      enabled: true