spring:
  jpa:
    database: ${DATABASE:HSQL}
    hibernate.ddl-auto: ${DDL-AUTO:create-drop}
    properties:
      hibernate.dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.HSQLDialect}
  datasource:
    driverClassName: ${DRIVER_CLASS_NAME:org.hsqldb.jdbcDriver}
    url: ${URL:jdbc:hsqldb:mem:scratchdb}
    username: ${USERNAME:sa}
    password: ${PASSWORD:}
  profiles:
    active: ${DEV_PROFILE:test}